### ISSUE TITLE
SQLite3::exec(): database is locked

### ISSUE THREAD

**Issue by psntr** [bnomei/kirby3-sqlite-cachedriver#2]
Hi,

As I'm using the plugin now for a couple of weeks, every now and then I'm facing this issue where the panel or sometime in the frontend the following message:
"SQLite3::exec(): database is locked"

I remember in my previous issue you mentionned:

yeah that can happen if plugin did not properly close the connection due to a timeout etc. but i encountered it rarely. since everything in boost is just a cache you can simply delete the sqlite file.

or you could try
`sqlite3 mydata.db ".dump" | sqlite3 new.db` or `sqlite3 broken.db ".recover" | sqlite3 new.db`
https://stackoverflow.com/questions/18259692/how-to-recover-a-corrupt-sqlite3-database

_Originally posted by @bnomei in https://github.com/bnomei/kirby3-boost/issues/3#issuecomment-996616778_

Would it be possible to automatically flush the SQL file, because on production level, the editor wouldn't be able to run such command or manually delete the SQL file.

Looking forward to hear from you.

**Comment by bnomei** [comment]
i dont think the plugin should just delete the cache silently and start anew to recover automatically. that would mask the issue.

the problem is also not directly connected to boost plugin itself but more to the sqlite cache driver. thus i moved the issue to that repo.

what you can do to make the db connection more stable is change the pragmas. by default its optimized for speed not reliability. if these do not work for your setup you can change them or even remove them all.

https://github.com/bnomei/kirby3-sqlite-cachedriver/blob/c3dc55819587848c973ef0d66a5bb1ba6353f859/index.php#L22

here is how to change that...


**site/config/config.php**
```php
return [
    // other options
   'bnomei.sqlite-cachedriver.pragmas-construct' => [
       // your pragmas or none
   ],
   'bnomei.sqlite-cachedriver.pragmas-destruct' => [
       // your pragmas or none
   ],
];
```

**Comment by bnomei** [comment]
⚠️ every time you change the pragmas you will have to delete the db to make it work.

**Comment by psntr** [comment]
Thank you for the information! Good to know that I can change that with the pragmas options. I will play around and also check on my server if I can boost the memory or the timeout.
